### ISSUE TITLE
Minio

### ISSUE THREAD

**Issue by gjelenc** [douglascrp/alfresco-cloud-store#12]
Anyone tried this connector with Minio (https://www.minio.io/) ?

**Comment by douglascrp** [comment]
I don't think so.
But if you are considering using your own storage, why using something to "emulate" S3, if you could use something way more simpler, like having your Alfresco server connecting into the storage using, for example, NFS, and let Alfresco work just like any normal setup reading and writing into this mounted NFS disk?

**Comment by douglascrp** [comment]
And I am closing this, as this is not directly related with the addon itself.
