### ISSUE TITLE
running apply_amps.sh

### ISSUE THREAD

**Issue by digcat** [douglascrp/alfresco-cloud-store#9]
after compiling amp, applying to war using standard apply_amps command, I see this ERROR.  There are other amps present, but not errors get generated with them, only if this amp is added.  Does that jar ring any bells? 

00060000 ERROR: The amp will overwrite an existing file in the war '/WEB-INF/lib/jackson-mapper-asl-1.9.13.jar'. Execution halted.  By specifying -force , you can force installation of AMP regardless of the current war state

**Comment by douglascrp** [comment]
@digcat Is this still a problem?

**Comment by digcat** [comment]
hi douglascrp, yes ill close this, everythings moved along.
